version: '3.8'
services:
  backend:
    # Point to the image you pushed to a registry
    image: lucianxconst/travelswipe-backend
    ports:
      - '80:5001' # Azure expects the app to listen on port 80 or 8080 externally
    environment:
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=production
    restart: always
